### NETWORKS ###
networks:
  web:
    name: web
    driver: bridge
    external: false
    attachable: true
  database:
    name: database
    driver: bridge
    external: false
    attachable: true

services:
  ca-api-dev:
    image: lab-ca-api-dev
    container_name: lab-ca-api-dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8810:8810"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_FLYWAY_ENABLED=${SPRING_FLYWAY_ENABLED}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SECURE=${MINIO_SECURE}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - BACK_BASE_URL=${BACK_BASE_URL}
      - FRONT_BASE_URL=${FRONT_BASE_URL}
      - FRONT_PORT=${FRONT_PORT}
      - TZ=America/Sao_Paulo
    labels:
      # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.ca-api-dev.rule=Host(`ca-api-dev.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.ca-api-dev.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ca-api-dev.entrypoints=websecure"
      - "traefik.http.services.ca-api-dev.loadbalancer.server.port=8810"
      # Em labels do seu serviço:
      - "traefik.http.routers.ca-api-dev.middlewares=websocket-headers"
      - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=Upgrade"

    restart: unless-stopped
    networks:
      - web
      - database

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ca_lab
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - database
    depends_on:
      - postgresql

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - web
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

volumes:
  postgres_data:
  minio_data: