version: '3.9'

### NETWORKS ###
networks:
  web:
    name: web
    driver: bridge
    external: false
    attachable: true
  database:
    name: database
    driver: bridge
    external: false
    attachable: true

services:
  lab-ca-api:
    image: lab-ca-api:${BUILD_NUMBER}
    container_name: lab-ca-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8813:8813"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SECURE=${MINIO_SECURE}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - FRONT_BASE_URL=${FRONT_BASE_URL}
      - FRONT_PORT=${FRONT_PORT}
      - BACK_BASE_URL=${BACK_BASE_URL}
      - TZ=America/Sao_Paulo
    labels:
      # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.lab-ca-api.rule=Host(`lab-ca-api.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.lab-ca-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.lab-ca-api.entrypoints=websecure"
    restart: unless-stopped
    networks:
      - web
      - database
      
