create table project_student (project_id bigint not null, user_id bigint not null);
create table tb_analysis (id bigserial not null, description varchar(255), name varchar(255), equipment_id bigint, primary key (id));
create table tb_domain_role (id bigserial not null, domain varchar(255), role smallint check (role between 0 and 4), primary key (id));
create table tb_email_code (id bigserial not null, code varchar(255), created_at timestamp(6), validate_at timestamp(6), user_id bigint, primary key (id));
create table tb_email_config (id bigserial not null, email varchar(255), host varchar(255), password varchar(255), port integer, primary key (id));
create table tb_email_log (id bigint not null, body text, created_at timestamp(6), email_from varchar(255), email_to varchar(255), owner_ref varchar(255), status_email varchar(255) check (status_email in ('PROCESSING','SENT','ERROR')), subject varchar(255), primary key (id));
create table tb_equipment (id bigserial not null, model varchar(255), name varchar(255), short_name varchar(255), status smallint check (status between 0 and 1), value_hour_external numeric(38,2), value_hour_partner numeric(38,2), value_hour_utfpr numeric(38,2), value_sample_external numeric(38,2), value_sample_partner numeric(38,2), value_sample_utfpr numeric(38,2), primary key (id));
create table tb_partner (id bigserial not null, cnpj varchar(255), name varchar(255), status smallint check (status between 0 and 1), primary key (id));
create table tb_permission (id bigserial not null, action smallint check (action between 0 and 3), description varchar(50) not null, user_id bigint, primary key (id));
create table tb_project (id bigserial not null, description varchar(255), subject varchar(255), user_id bigint, primary key (id));
create table tb_solicitation (id bigserial not null, amount_hours numeric(38,2), amount_samples integer, created_at timestamp(6), form jsonb, methodology_description varchar(255), observation varchar(255), other_project_nature varchar(255), paid boolean not null, price numeric(38,2), project_nature varchar(255) check (project_nature in ('MASTERS_THESIS','DOCTORATE_DISSERTATION','UNDERGRADUATE_THESIS','INTERNSHIP_PROJECT','SCIENTIFIC_INITIATION','EXTENSION_PROJECT','RESEARCH_PROJECT','TEACHING_PROJECT','OTHER')), schedule_date timestamp(6), status smallint check (status between 0 and 7), total_price numeric(38,2), updated_at timestamp(6), analysis_id bigint, user_id bigint, equipment_id bigint, professor_id bigint, project_id bigint, user_updated_id bigint, primary key (id));
create table tb_solicitation_attachments (id bigserial not null, attachments varchar(255) check (attachments in ('REPORT','TICKET','INVOICE','ATTACHMENT')), content_type varchar(255), file_name varchar(255), url varchar(255), technical_report_id bigint, primary key (id));
create table tb_solicitation_historic (id bigserial not null, created_at timestamp(6), observation varchar(255), status smallint check (status between 0 and 7), created_by bigint, solicitation_id bigint, primary key (id));
create table tb_student_professor (id bigserial not null, approved boolean, created_at date, professor bigint, student bigint, primary key (id));
create table tb_student_solicitation (id bigserial not null, creation_date timestamp(6), finish_date timestamp(6), status smallint check (status between 0 and 4), finished_by bigint, solicited_by bigint, solicited_to bigint, primary key (id));
create table tb_transaction (id bigserial not null, created_at timestamp(6), description varchar(255), total_value numeric(38,2), created_by bigint, solicitation_id bigint, updated_by bigint, user_id bigint, primary key (id));
create table tb_user (id bigserial not null, balance numeric(38,2), cpf_cnpj varchar(255), created_at timestamp(6), email varchar(255), email_verified boolean, name varchar(255), password varchar(255), ra_siape varchar(255), role smallint check (role between 0 and 4), status smallint check (status between 0 and 1), updated_at timestamp(6), partner_id bigint, primary key (id));
alter table if exists tb_domain_role drop constraint if exists unique_domain_role;
alter table if exists tb_domain_role add constraint unique_domain_role unique (domain);
alter table if exists tb_email_code drop constraint if exists UK_raf31370qu7jml83qgdjwn8t8;
alter table if exists tb_email_code add constraint UK_raf31370qu7jml83qgdjwn8t8 unique (user_id);
alter table if exists tb_solicitation drop constraint if exists UK_4y998iy51sutqya4jwf15v4mc;
alter table if exists tb_solicitation add constraint UK_4y998iy51sutqya4jwf15v4mc unique (equipment_id);
alter table if exists tb_solicitation drop constraint if exists UK_34k1a84smw2eocvjrc16b3mae;
alter table if exists tb_solicitation add constraint UK_34k1a84smw2eocvjrc16b3mae unique (project_id);
alter table if exists tb_student_professor drop constraint if exists UK_7gqtqjjfotvijadiek8bu8uio;
alter table if exists tb_student_professor add constraint UK_7gqtqjjfotvijadiek8bu8uio unique (professor);
alter table if exists tb_student_professor drop constraint if exists UK_74159qi77clmtsls1u7emvo0p;
alter table if exists tb_student_professor add constraint UK_74159qi77clmtsls1u7emvo0p unique (student);
alter table if exists tb_user drop constraint if exists set_unique_email;
alter table if exists tb_user add constraint set_unique_email unique (email);
create sequence tb_email_log_seq start with 1 increment by 50;
alter table if exists project_student add constraint FKnv8q0novh3yhnbaq0tvq54jj4 foreign key (user_id) references tb_user;
alter table if exists project_student add constraint FKrfndy6dlk9lmq59g8u3t735up foreign key (project_id) references tb_project;
alter table if exists tb_analysis add constraint FK942vrnty41a31q2jcv4xvgdac foreign key (equipment_id) references tb_equipment;
alter table if exists tb_email_code add constraint FKk5qogn023wep95dh3yww10uws foreign key (user_id) references tb_user;
alter table if exists tb_permission add constraint FKcdbrluhn9jgyn5de6fwr4fpv9 foreign key (user_id) references tb_user;
alter table if exists tb_project add constraint FKmo8o99rcuh1bqkhh95uk226vw foreign key (user_id) references tb_user;
alter table if exists tb_solicitation add constraint FKdgtvi6jd4wlwy0h6d6pkxbvnv foreign key (analysis_id) references tb_analysis;
alter table if exists tb_solicitation add constraint FK9hhty4lawki2ldb3qh50rug65 foreign key (user_id) references tb_user;
alter table if exists tb_solicitation add constraint FKti1m0p2vryxkvgx7uyj3dss1p foreign key (equipment_id) references tb_equipment;
alter table if exists tb_solicitation add constraint FKg81av27wvobhlh7yj2m2r29um foreign key (professor_id) references tb_user;
alter table if exists tb_solicitation add constraint FKdw5mecywrq858t9qvcv4u4slb foreign key (project_id) references tb_project;
alter table if exists tb_solicitation add constraint FKiv8t82rgjp7ru5igcq7eu6psc foreign key (user_updated_id) references tb_user;
alter table if exists tb_solicitation_attachments add constraint FKs49ax4tgcewiv51dpryo44xao foreign key (technical_report_id) references tb_solicitation;
alter table if exists tb_solicitation_historic add constraint FKeh8rihsb9w5qorvwq53qt2yg foreign key (created_by) references tb_user;
alter table if exists tb_solicitation_historic add constraint FK52gm4wvo3ye32xunl257t3pyt foreign key (solicitation_id) references tb_solicitation;
alter table if exists tb_student_professor add constraint FKru5xjbhqyjmv7k70g6ifvidjy foreign key (professor) references tb_user;
alter table if exists tb_student_professor add constraint FKhlsj4g775lmodv0qvpst8f2uf foreign key (student) references tb_user;
alter table if exists tb_student_solicitation add constraint FKlliw0yj8olqhyh9prpdyn4d6y foreign key (finished_by) references tb_user;
alter table if exists tb_student_solicitation add constraint FKkaic9wktv2tiy87bdabvd23d9 foreign key (solicited_by) references tb_user;
alter table if exists tb_student_solicitation add constraint FKr6hialw3bht2y59gqkhbt9481 foreign key (solicited_to) references tb_user;
alter table if exists tb_transaction add constraint FKjb5qnoog1c3py5smh9v0a5kk4 foreign key (created_by) references tb_user;
alter table if exists tb_transaction add constraint FKjsj1mnycfll8c6aslewlt7j7o foreign key (solicitation_id) references tb_solicitation;
alter table if exists tb_transaction add constraint FK5dd7p67lhqlc7mequnuuye60p foreign key (updated_by) references tb_user;
alter table if exists tb_transaction add constraint FK7f3wtdpf61kpwpm1p7ygh2ccf foreign key (user_id) references tb_user;
alter table if exists tb_user add constraint FKbqplyqefdhku3s1nop5h9r4i7 foreign key (partner_id) references tb_partner;
alter table if exists tb_email_code alter column created_at set data type timestamp(6);
alter table if exists tb_email_code alter column validate_at set data type timestamp(6);
alter table if exists tb_email_log alter column body set data type text;
alter table if exists tb_email_log alter column created_at set data type timestamp(6);
alter table if exists tb_solicitation alter column created_at set data type timestamp(6);
alter table if exists tb_solicitation alter column schedule_date set data type timestamp(6);
alter table if exists tb_solicitation alter column updated_at set data type timestamp(6);
alter table if exists tb_solicitation_historic alter column created_at set data type timestamp(6);
alter table if exists tb_student_solicitation alter column creation_date set data type timestamp(6);
alter table if exists tb_student_solicitation alter column finish_date set data type timestamp(6);
alter table if exists tb_transaction alter column created_at set data type timestamp(6);
alter table if exists tb_user alter column created_at set data type timestamp(6);
alter table if exists tb_user alter column updated_at set data type timestamp(6);
