create sequence tb_email_log_seq start with 1 increment by 50;
create table if not exists tb_project_student (project_id bigint not null, user_id bigint not null);
create table if not exists tb_analysis (equipment_id bigint, id bigserial not null, description varchar(255), name varchar(255), primary key (id));
create table if not exists tb_domain_role (role smallint check (role between 0 and 4), id bigserial not null, domain varchar(255), primary key (id), constraint unique_domain_role unique (domain));
create table if not exists tb_email_code (created_at timestamp(6), id bigserial not null, user_id bigint unique, validate_at timestamp(6), code varchar(255), primary key (id));
create table if not exists tb_email_config (port integer, id bigserial not null, email varchar(255), host varchar(255), password varchar(255), primary key (id));
create table if not exists tb_email_log (created_at timestamp(6), id bigint not null, body text, email_from varchar(255), email_to varchar(255), owner_ref varchar(255), status_email varchar(255) check (status_email in ('PROCESSING','SENT','ERROR')), subject varchar(255), primary key (id));
create table if not exists tb_equipment (status smallint check (status between 0 and 1), value_hour_external numeric(38,2), value_hour_partner numeric(38,2), value_hour_utfpr numeric(38,2), value_sample_external numeric(38,2), value_sample_partner numeric(38,2), value_sample_utfpr numeric(38,2), id bigserial not null, model varchar(255), name varchar(255), short_name varchar(255), primary key (id));
create table if not exists tb_partner (status smallint check (status between 0 and 1), id bigserial not null, cnpj varchar(20) not null unique, name varchar(255), primary key (id));
create table if not exists tb_permission (action smallint check (action between 0 and 3), id bigserial not null, user_id bigint, description varchar(50) not null, primary key (id));
create table if not exists tb_project (id bigserial not null, user_id bigint, description varchar(255), subject varchar(255), primary key (id));
create table if not exists tb_solicitation (amount_hours numeric(38,2), amount_samples integer, paid boolean not null, price numeric(38,2), status smallint check (status between 0 and 7), total_price numeric(38,2), analysis_id bigint, created_at timestamp(6), equipment_id bigint unique, id bigserial not null, professor_id bigint, project_id bigint unique, schedule_date timestamp(6), updated_at timestamp(6), user_id bigint, user_updated_id bigint, methodology_description varchar(255), observation varchar(255), other_project_nature varchar(255), project_nature varchar(255) check (project_nature in ('MASTERS_THESIS','DOCTORATE_DISSERTATION','UNDERGRADUATE_THESIS','INTERNSHIP_PROJECT','SCIENTIFIC_INITIATION','EXTENSION_PROJECT','RESEARCH_PROJECT','TEACHING_PROJECT','OTHER')), form jsonb, primary key (id));
create table if not exists tb_solicitation_attachments (id bigserial not null, attachment_id bigint, solicitation_id bigint);
create table if not exists tb_solicitation_historic (status smallint check (status between 0 and 7), created_at timestamp(6), created_by bigint, id bigserial not null, solicitation_id bigint, observation varchar(255), primary key (id));
create table if not exists tb_student_professor (approved smallint check (approved between 0 and 2), created_at date, id bigserial not null, professor bigint unique, student bigint unique, primary key (id));
create table if not exists tb_student_solicitation (status smallint check (status between 0 and 4), creation_date timestamp(6), finish_date timestamp(6), finished_by bigint, id bigserial not null, solicited_by bigint, solicited_to bigint, primary key (id));
create table if not exists tb_transaction (total_value numeric(38,2), created_at timestamp(6), created_by bigint, id bigserial not null, solicitation_id bigint, updated_by bigint, user_id bigint, description varchar(255), primary key (id));
create table if not exists tb_user (balance numeric(38,2), email_verified boolean, role smallint check (role between 0 and 4), status smallint check (status between 0 and 1), type smallint check (type between 0 and 1), created_at timestamp(6), id bigserial not null, partner_id bigint, updated_at timestamp(6), cpf_cnpj varchar(255) not null unique, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, ra_siape varchar(255), primary key (id), constraint set_unique_email unique (email));
alter table if exists tb_project_student add constraint FKnv8q0novh3yhnbaq0tvq54jj4 foreign key (user_id) references tb_user;
alter table if exists tb_project_student add constraint FKrfndy6dlk9lmq59g8u3t735up foreign key (project_id) references tb_project;
alter table if exists tb_analysis add constraint FK942vrnty41a31q2jcv4xvgdac foreign key (equipment_id) references tb_equipment;
alter table if exists tb_email_code add constraint FKk5qogn023wep95dh3yww10uws foreign key (user_id) references tb_user;
alter table if exists tb_permission add constraint FKcdbrluhn9jgyn5de6fwr4fpv9 foreign key (user_id) references tb_user;
alter table if exists tb_project add constraint FKmo8o99rcuh1bqkhh95uk226vw foreign key (user_id) references tb_user;
alter table if exists tb_solicitation add constraint FKdgtvi6jd4wlwy0h6d6pkxbvnv foreign key (analysis_id) references tb_analysis;
alter table if exists tb_solicitation add constraint FK9hhty4lawki2ldb3qh50rug65 foreign key (user_id) references tb_user;
alter table if exists tb_solicitation add constraint FKti1m0p2vryxkvgx7uyj3dss1p foreign key (equipment_id) references tb_equipment;
alter table if exists tb_solicitation add constraint FKg81av27wvobhlh7yj2m2r29um foreign key (professor_id) references tb_user;
alter table if exists tb_solicitation add constraint FKdw5mecywrq858t9qvcv4u4slb foreign key (project_id) references tb_project;
alter table if exists tb_solicitation add constraint FKiv8t82rgjp7ru5igcq7eu6psc foreign key (user_updated_id) references tb_user;
alter table if exists tb_solicitation_attachments add constraint FKs49ax4tgcewiv51dpryo44xao foreign key (attachment_id) references tb_attachment;
alter table if exists tb_solicitation_attachments add constraint FKs50ax4tgcew3215pryo4923so foreign key (solicitation_id) references tb_solicitation;
alter table if exists tb_solicitation_historic add constraint FKeh8rihsb9w5qorvwq53qt2yg foreign key (created_by) references tb_user;
alter table if exists tb_solicitation_historic add constraint FK52gm4wvo3ye32xunl257t3pyt foreign key (solicitation_id) references tb_solicitation;
alter table if exists tb_student_professor add constraint FKru5xjbhqyjmv7k70g6ifvidjy foreign key (professor) references tb_user;
alter table if exists tb_student_professor add constraint FKhlsj4g775lmodv0qvpst8f2uf foreign key (student) references tb_user;
alter table if exists tb_student_solicitation add constraint FKlliw0yj8olqhyh9prpdyn4d6y foreign key (finished_by) references tb_user;
alter table if exists tb_student_solicitation add constraint FKkaic9wktv2tiy87bdabvd23d9 foreign key (solicited_by) references tb_user;
alter table if exists tb_student_solicitation add constraint FKr6hialw3bht2y59gqkhbt9481 foreign key (solicited_to) references tb_user;
alter table if exists tb_transaction add constraint FKjb5qnoog1c3py5smh9v0a5kk4 foreign key (created_by) references tb_user;
alter table if exists tb_transaction add constraint FKjsj1mnycfll8c6aslewlt7j7o foreign key (solicitation_id) references tb_solicitation;
alter table if exists tb_transaction add constraint FK5dd7p67lhqlc7mequnuuye60p foreign key (updated_by) references tb_user;
alter table if exists tb_transaction add constraint FK7f3wtdpf61kpwpm1p7ygh2ccf foreign key (user_id) references tb_user;
alter table if exists tb_user add constraint FKbqplyqefdhku3s1nop5h9r4i7 foreign key (partner_id) references tb_partner;