UPDATE equipment SET short_name = 'HLPC' where name = 'Cromatógrafo líquido de alta eficiência - HPLC (modelo LC920, Varian)';
UPDATE equipment SET short_name = 'CG-EM' where name = 'Cromatógrafo a gás acoplado com espectrômetro de massa (CG-EM) (modelo 431GC-210MS, Varian)';
UPDATE equipment SET short_name = 'TGA-DTA-DSC' where name = 'Analisador termogravimétrico - TGA-DTA-DSC (modelo SDTQ600, TA Instruments)';
UPDATE equipment SET short_name = 'DSC' where name = 'Calorímetro diferencial exploratório - DSC (modelo Q20, TA instruments)';
UPDATE equipment SET short_name = 'MEV' where name = 'Microscópio Eletrônico de Varredura – MEV (modelo TM3000, Hitachi)';
UPDATE equipment SET short_name = 'DRX' where name = 'Difratômetro de Raios-X - DRX (modelo Miniflex 600, Rigaku)';
UPDATE equipment SET short_name = 'FT-NIR' where name = 'Espectrômetro de Infravermelho na região do próximo com Transformada de Fourier - FT-NIR (modelo MPA, BRUKER)';
UPDATE equipment SET short_name = 'FT-MIR' where name = 'Espectrômetro de Infravermelho na região do Médio com Transformada de Fourier - FT-MIR (modelo Frontier, Perkin Elmer)';
UPDATE equipment SET short_name = 'UV-Vis' where name = 'Espectrofotômetro de Absorção Molecular - UV-Vis (modelo LAMBDA 45, Perkin Elmer)';
UPDATE equipment SET short_name = 'A ATÔMICA' where name = 'Espectrômetro de Absorção Atômica - A ATÔMICA (modelo PinAAcle 900T, Perkin Elmer)';
UPDATE equipment SET short_name = 'A ELEMENTAR' where name = 'Analisador elementar de CHNS-O - A ELEMENTAR (modelo Euro EA, Euro Vector)';