-- public.domain_role definition

-- Drop table

-- DROP TABLE public.domain_role;

CREATE TABLE public.domain_role (
                                    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    "domain" varchar(255) NULL,
                                    "role" int4 NULL,
                                    CONSTRAINT domain_role_pkey PRIMARY KEY (id),
                                    CONSTRAINT unique_domain_role UNIQUE (domain)
);