--EMAIL-CODE
--ALTER TABLE EMAIL_CODE ADD COLUMN CREATED_AT TIMESTAMP; --JÁ EXISTE NO BANCO

--EmailModel
ALTER TABLE TB_EMAIL ADD COLUMN CREATED_AT TIMESTAMP;
ALTER TABLE TB_EMAIL ADD COLUMN CREATED_BY VARCHAR(255);

--Equipament
ALTER TABLE EQUIPMENT ADD COLUMN CREATED_AT TIMESTAMP;
ALTER TABLE EQUIPMENT ADD COLUMN CREATED_BY VARCHAR(255);
ALTER TABLE EQUIPMENT ADD COLUMN MODIFIED_AT TIMESTAMP;
ALTER TABLE EQUIPMENT ADD COLUMN MODIFIED_BY VARCHAR(255);

--Partner
ALTER TABLE PARTNER ADD COLUMN CREATED_AT TIMESTAMP;
ALTER TABLE PARTNER ADD COLUMN CREATED_BY VARCHAR(255);
ALTER TABLE PARTNER ADD COLUMN MODIFIED_AT TIMESTAMP;
ALTER TABLE PARTNER ADD COLUMN MODIFIED_BY VARCHAR(255);

--Project
ALTER TABLE PROJECT ADD COLUMN CREATED_AT TIMESTAMP;
ALTER TABLE PROJECT ADD COLUMN CREATED_BY VARCHAR(255);
ALTER TABLE PROJECT ADD COLUMN MODIFIED_AT TIMESTAMP;
ALTER TABLE PROJECT ADD COLUMN MODIFIED_BY VARCHAR(255);

--TechnicalReport
ALTER TABLE TECHNICAL_REPORT  ADD COLUMN CREATED_AT TIMESTAMP;
ALTER TABLE TECHNICAL_REPORT ADD COLUMN CREATED_BY VARCHAR(255);
ALTER TABLE TECHNICAL_REPORT ADD COLUMN MODIFIED_AT TIMESTAMP;
ALTER TABLE TECHNICAL_REPORT ADD COLUMN MODIFIED_BY VARCHAR(255);

--Transaction
ALTER TABLE TRANSACTION ADD COLUMN CREATED_BY VARCHAR(255);
UPDATE TRANSACTION SET CREATED_BY = TRANSACTION.CREATE_BY;
ALTER TABLE TRANSACTION DROP COLUMN CREATE_BY;

--Solicitation
ALTER TABLE SOLICITATION ADD COLUMN CREATED_AT TIMESTAMP;
ALTER TABLE SOLICITATION ADD COLUMN CREATED_BY VARCHAR(255);
UPDATE SOLICITATION SET CREATED_BY = (SELECT EMAIL FROM USERS WHERE ID = CREATOR_ID);
ALTER TABLE SOLICITATION DROP COLUMN CREATOR_ID;
ALTER TABLE SOLICITATION ADD COLUMN MODIFIED_AT TIMESTAMP;
ALTER TABLE SOLICITATION ADD COLUMN MODIFIED_BY VARCHAR(255);

--StudantSolicitation
ALTER TABLE STUDENT_SOLICITATION ADD COLUMN CREATED_AT TIMESTAMP;
UPDATE STUDENT_SOLICITATION SET CREATED_AT = CREATION_DATE;
ALTER TABLE STUDENT_SOLICITATION DROP CREATION_DATE;
ALTER TABLE STUDENT_SOLICITATION ADD COLUMN CREATED_BY VARCHAR(255);
ALTER TABLE STUDENT_SOLICITATION ADD COLUMN MODIFIED_AT TIMESTAMP;
ALTER TABLE STUDENT_SOLICITATION ADD COLUMN MODIFIED_BY VARCHAR(255);

--Users
ALTER TABLE USERS ADD COLUMN MODIFIED_AT TIMESTAMP;
ALTER TABLE USERS ADD COLUMN MODIFIED_BY VARCHAR(255);
UPDATE USERS SET MODIFIED_AT = UPDATED_AT;
ALTER TABLE USERS DROP COLUMN UPDATED_AT;