-- Cria as tabelas

-- public.configemail definition

-- Drop table

-- DROP TABLE public.configemail;

CREATE TABLE public.configemail (
                                    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    email_from varchar(255) NULL,
                                    password_email_from varchar(255) NULL,
                                    send_host varchar(255) NULL,
                                    send_port int4 NULL,
                                    CONSTRAINT configemail_pkey PRIMARY KEY (id)
);


-- public.equipment definition

-- Drop table

-- DROP TABLE public.equipment;

CREATE TABLE public.equipment (
                                  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  form varchar(255) NULL,
                                  "name" varchar(255) NULL,
                                  status int4 NULL,
                                  value_hour_partner numeric(19, 2) NULL,
                                  value_hour_pf_pj numeric(19, 2) NULL,
                                  value_hour_utfpr numeric(19, 2) NULL,
                                  value_sample_partner numeric(19, 2) NULL,
                                  value_sample_pf_pj numeric(19, 2) NULL,
                                  value_sample_utfpr numeric(19, 2) NULL,
                                  CONSTRAINT equipment_pkey PRIMARY KEY (id)
);

-- public.partner definition

-- Drop table

-- DROP TABLE public.partner;

CREATE TABLE public.partner (
                                id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                "name" varchar(255) NULL,
                                CONSTRAINT partner_pkey PRIMARY KEY (id)
);


-- public.tb_email definition

-- Drop table

-- DROP TABLE public.tb_email;

CREATE TABLE public.tb_email (
                                 email_id int8 NOT NULL,
                                 email_from varchar(255) NULL,
                                 email_to varchar(255) NULL,
                                 owner_ref varchar(255) NULL,
                                 send_date_email timestamp NULL,
                                 status_email int4 NULL,
                                 subject varchar(255) NULL,
                                 "text" text NULL,
                                 CONSTRAINT tb_email_pkey PRIMARY KEY (email_id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              balance numeric(19, 2) NULL,
                              cnpj varchar(255) NULL,
                              cpf varchar(255) NULL,
                              created_at timestamp NULL,
                              email varchar(255) NULL,
                              email_verified bool NULL,
                              "name" varchar(255) NULL,
                              "password" varchar(255) NULL,
                              ra varchar(255) NULL,
                              "role" int4 NULL,
                              siape varchar(255) NULL,
                              status int4 NULL,
                              updated_at timestamp NULL,
                              partner_id int8 NULL,
                              CONSTRAINT setuniqueemail UNIQUE (email),
                              CONSTRAINT users_pkey PRIMARY KEY (id),
                              CONSTRAINT fkhylv22iow7h4it5pd074wll22 FOREIGN KEY (partner_id) REFERENCES public.partner(id)
);


-- public.email_code definition

-- Drop table

-- DROP TABLE public.email_code;

CREATE TABLE public.email_code (
                                   id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   code varchar(255) NULL,
                                   created_at timestamp NULL,
                                   validate_at timestamp NULL,
                                   user_id int8 NULL,
                                   CONSTRAINT email_code_pkey PRIMARY KEY (id),
                                   CONSTRAINT fkp50i69palc7sgmpjtxr0ruky1 FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public."permission" definition

-- Drop table

-- DROP TABLE public."permission";

CREATE TABLE public."permission" (
                                     id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     "action" int4 NULL,
                                     description varchar(50) NOT NULL,
                                     user_id int8 NULL,
                                     CONSTRAINT permission_pkey PRIMARY KEY (id),
                                     CONSTRAINT fktpvwdvckg86mpuk9o2j1h6t15 FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.project definition

-- Drop table

-- DROP TABLE public.project;

CREATE TABLE public.project (
                                id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                description varchar(255) NULL,
                                subject varchar(255) NULL,
                                teacher_id int8 NULL,
                                CONSTRAINT project_pkey PRIMARY KEY (id),
                                CONSTRAINT fktka67rsuw03klpuiqh25sy82t FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);


-- public.project_student definition

-- Drop table

-- DROP TABLE public.project_student;

CREATE TABLE public.project_student (
                                        project_id int8 NOT NULL,
                                        user_id int8 NOT NULL,
                                        CONSTRAINT fkrwrqi8lnwc20jdsl0di7595dt FOREIGN KEY (project_id) REFERENCES public.project(id),
                                        CONSTRAINT fksfigybcnck4hluwvcmwhncaji FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.solicitation definition

-- Drop table

-- DROP TABLE public.solicitation;

CREATE TABLE public.solicitation (
                                     id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     description varchar(255) NULL,
                                     fields varchar(255) NULL,
                                     other_project_nature varchar(255) NULL,
                                     project_nature varchar(255) NULL,
                                     status int4 NULL,
                                     type_user varchar(255) NULL,
                                     value numeric(19, 2) NULL,
                                     creator_id int8 NULL,
                                     equipment_id int8 NULL,
                                     project_id int8 NULL,
                                     CONSTRAINT solicitation_pkey PRIMARY KEY (id),
                                     CONSTRAINT fkdirxqwdmu04apscb6ad3b1puo FOREIGN KEY (creator_id) REFERENCES public.users(id),
                                     CONSTRAINT fkmabndy0g8vd853djg18ktagd FOREIGN KEY (equipment_id) REFERENCES public.equipment(id),
                                     CONSTRAINT fkt9quqi6roy4qh3m934b2lfdvj FOREIGN KEY (project_id) REFERENCES public.project(id)
);


-- public.student_solicitation definition

-- Drop table

-- DROP TABLE public.student_solicitation;

CREATE TABLE public.student_solicitation (
                                             id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             creation_date timestamp NULL,
                                             finish_date timestamp NULL,
                                             status int4 NULL,
                                             finished_by int8 NULL,
                                             solicitated_by int8 NULL,
                                             solicitated_to int8 NULL,
                                             CONSTRAINT student_solicitation_pkey PRIMARY KEY (id),
                                             CONSTRAINT fkcr5ggvawb7p0nb6lp174eh93q FOREIGN KEY (solicitated_to) REFERENCES public.users(id),
                                             CONSTRAINT fkcsa8jdevheox1spo9l7ik97jj FOREIGN KEY (finished_by) REFERENCES public.users(id),
                                             CONSTRAINT fkmifnpcha0rdj2xk1a86dvhkqv FOREIGN KEY (solicitated_by) REFERENCES public.users(id)
);


-- public.student_teacher definition

-- Drop table

-- DROP TABLE public.student_teacher;

CREATE TABLE public.student_teacher (
                                        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        aproved bool NULL,
                                        created_at date NULL,
                                        student int8 NULL,
                                        teacher int8 NULL,
                                        CONSTRAINT student_teacher_pkey PRIMARY KEY (id),
                                        CONSTRAINT fkec7eqsd3889dvckiddeud9q5o FOREIGN KEY (student) REFERENCES public.users(id),
                                        CONSTRAINT fklrr40d5nsa0esws0r4an2vw5q FOREIGN KEY (teacher) REFERENCES public.users(id)
);


-- public.technical_report definition

-- Drop table

-- DROP TABLE public.technical_report;

CREATE TABLE public.technical_report (
                                         id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                         amount_hours int4 NULL,
                                         amount_samples int4 NULL,
                                         "date" timestamp NULL,
                                         description varchar(255) NULL,
                                         price float4 NULL,
                                         solicitation_id int8 NULL,
                                         CONSTRAINT technical_report_pkey PRIMARY KEY (id),
                                         CONSTRAINT fkqhvxcop1jsgipt7tn9n809306 FOREIGN KEY (solicitation_id) REFERENCES public.solicitation(id)
);


-- public."transaction" definition

-- Drop table

-- DROP TABLE public."transaction";

CREATE TABLE public."transaction" (
                                      id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      created_at timestamp NULL,
                                      current_balance numeric(19, 2) NULL,
                                      description varchar(255) NULL,
                                      old_balance numeric(19, 2) NULL,
                                      "type" int4 NULL,
                                      value numeric(19, 2) NULL,
                                      create_by int8 NULL,
                                      solicitation int8 NULL,
                                      user_id int8 NULL,
                                      CONSTRAINT transaction_pkey PRIMARY KEY (id),
                                      CONSTRAINT fk3j8ddxa0qdprbeqdibpn3v06p FOREIGN KEY (create_by) REFERENCES public.users(id),
                                      CONSTRAINT fk9yqed84n57fdj9jbrplwrf4d5 FOREIGN KEY (solicitation) REFERENCES public.solicitation(id),
                                      CONSTRAINT fkanjpo5tiapru7an6cw4cu37y4 FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.audit definition

-- Drop table

-- DROP TABLE public.audit;

CREATE TABLE public.audit (
                              id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              change_date timestamp NULL,
                              new_status int4 NULL,
                              solicitation_id int8 NULL,
                              updated_by_id int8 NULL,
                              CONSTRAINT audit_pkey PRIMARY KEY (id),
                              CONSTRAINT fkngd8s2knp1x3vmjtpr76y1yxc FOREIGN KEY (solicitation_id) REFERENCES public.solicitation(id),
                              CONSTRAINT fks3q23vuv2g0f9i92cn26kemjl FOREIGN KEY (updated_by_id) REFERENCES public.users(id)
);


-- public.multi_part_file_list definition

-- Drop table

-- DROP TABLE public.multi_part_file_list;

CREATE TABLE public.multi_part_file_list (
                                             id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             content_type varchar(255) NULL,
                                             file_name varchar(255) NULL,
                                             technical_report_id int8 NULL,
                                             CONSTRAINT multi_part_file_list_pkey PRIMARY KEY (id),
                                             CONSTRAINT fkgcd406n75ontsgm2crhqlq7jl FOREIGN KEY (technical_report_id) REFERENCES public.technical_report(id)
);