-- Cria as tabelas
-- public.tb_email_config definition
-- Drop table
-- DROP TABLE public.tb_email_config;
CREATE TABLE public.tb_email_config
(
    id       int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email    varchar(255) NULL,
    password varchar(255) NULL,
    host     varchar(255) NULL,
    port     int4         NULL,
    CONSTRAINT tb_email_config_pkey PRIMARY KEY (id)
);


-- public.equipment definition
-- Drop table
-- DROP TABLE public.equipment;
CREATE TABLE public.tb_equipment
(
    id                    int8           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"                varchar(512)   NULL,
    short_name            varchar(255)   NULL,
    model                 varchar(255)   NULL,
    status                int4           NULL,
    value_hour_partner    numeric(19, 2) NULL,
    value_hour_external   numeric(19, 2) NULL,
    value_hour_utfpr      numeric(19, 2) NULL,
    value_sample_partner  numeric(19, 2) NULL,
    value_sample_external numeric(19, 2) NULL,
    value_sample_utfpr    numeric(19, 2) NULL,
    CONSTRAINT tb_equipment_pkey PRIMARY KEY (id)
);

-- public.partner definition
-- Drop table
-- DROP TABLE public.partner;
CREATE TABLE public.tb_partner
(
    id     int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name   varchar(255) NULL,
    cnpj   varchar(18)  NULL,
    status varchar(255) NULL,
    CONSTRAINT tb_partner_pkey PRIMARY KEY (id)
);


-- public.tb_email definition
-- Drop table
-- DROP TABLE public.tb_email;
CREATE TABLE public.tb_email_log
(
    id              int8         NOT NULL,
    email_from      varchar(255) NULL,
    email_to        varchar(255) NULL,
    owner_ref       varchar(255) NULL,
    send_date_email timestamp    NULL,
    status_email    int4         NULL,
    subject         varchar(255) NULL,
    text            text         NULL,
    CONSTRAINT tb_email_log_pkey PRIMARY KEY (id)
);

-- public.tb_user definition
-- Drop table
-- DROP TABLE public.tb_user;
CREATE TABLE public.tb_user
(
    id             int8           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    balance        numeric(19, 2) NULL,
    cpf_cnpj       varchar(25)    NULL,
    created_at     timestamp      NULL,
    email          varchar(255)   NULL,
    email_verified bool           NULL,
    name           varchar(255)   NULL,
    password       varchar(255)   NULL,
    ra_siape       varchar(25)    NULL,
    role           int4           NULL,
    status         int4           NULL,
    updated_at     timestamp      NULL,
    partner_id     int8           NULL,
    CONSTRAINT set_unique_email UNIQUE (email),
    CONSTRAINT tb_user_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user_partner FOREIGN KEY (partner_id) REFERENCES public.tb_partner (id)
);

-- public.email_code definition
-- Drop table
-- DROP TABLE public.email_code;
CREATE TABLE public.tb_email_code
(
    id          int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code        varchar(255) NULL,
    created_at  timestamp    NULL,
    validate_at timestamp    NULL,
    user_id     int8         NULL,
    CONSTRAINT tb_email_code_pkey PRIMARY KEY (id),
    CONSTRAINT fk_email_code_user FOREIGN KEY (user_id) REFERENCES public.tb_user (id)
);

-- public.tb_permission definition
-- Drop table
-- DROP TABLE public.tb_permission;
CREATE TABLE public.tb_permission
(
    id          int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "action"    int4        NULL,
    description varchar(50) NOT NULL,
    user_id     int8        NULL,
    CONSTRAINT tb_permission_pkey PRIMARY KEY (id),
    CONSTRAINT fk_permission_user FOREIGN KEY (user_id) REFERENCES public.tb_user (id)
);

-- public.tb_project definition
-- Drop table
-- DROP TABLE public.tb_project;
CREATE TABLE public.tb_project
(
    id          int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description varchar(255) NULL,
    subject     varchar(255) NULL,
    user_id     int8         NULL,
    CONSTRAINT project_pkey PRIMARY KEY (id),
    CONSTRAINT fk_project_user FOREIGN KEY (user_id) REFERENCES public.tb_user (id)
);


-- public.tb_project_student definition
-- Drop table
-- DROP TABLE public.tb_project_student;
CREATE TABLE public.tb_project_student
(
    project_id int8 NOT NULL,
    user_id    int8 NOT NULL,
    CONSTRAINT fk_project_student_project FOREIGN KEY (project_id) REFERENCES public.tb_project (id),
    CONSTRAINT fk_project_student_user FOREIGN KEY (user_id) REFERENCES public.tb_user (id)
);

-- public.tb_analysis definition
-- Drop table
-- DROP TABLE public.tb_analysis;
CREATE TABLE public.tb_analysis
(
    id           int8          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name         varchar(255)  NULL,
    description  varchar(2048) NULL,
    equipment_id int8          NULL,
    CONSTRAINT tb_analysis_pkey PRIMARY KEY (id),
    CONSTRAINT fk_analysis_equipment FOREIGN KEY (equipment_id) REFERENCES public.tb_equipment (id)
);

-- public.tb_solicitation definition
-- Drop table
-- DROP TABLE public.tb_solicitation;
CREATE TABLE public.tb_solicitation
(
    id                      int8           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    methodology_description varchar(255)   NULL,
    form                    jsonb,
    project_nature          varchar(255)   NULL,
    other_project_nature    varchar(255)   NULL,
    status                  int4           NULL,
    amount_hours            float4         NULL,
    amount_samples          int4           NULL,
    price                   numeric(19, 2) NULL,
    total_price             numeric(19, 2) NULL,
    user_id                 int8           NULL,
    professor_id            int8           NULL,
    user_updated_id         int8           NULL,
    equipment_id            int8           NULL,
    project_id              int8           NULL,
    analysis_id             int8           NULL,
    created_at              timestamp      NULL,
    updated_at              timestamp      NULL,
    schedule_date           timestamp      NULL,
    observation             varchar(2048)  NULL,
    CONSTRAINT tb_solicitation_pkey PRIMARY KEY (id),
    CONSTRAINT fk_solicitation_user FOREIGN KEY (user_id) REFERENCES public.tb_user (id),
    CONSTRAINT fk_solicitation_professor FOREIGN KEY (professor_id) REFERENCES public.tb_user (id),
    CONSTRAINT fk_solicitation_user_update FOREIGN KEY (user_updated_id) REFERENCES public.tb_user (id),
    CONSTRAINT fk_solicitation_equipment FOREIGN KEY (equipment_id) REFERENCES public.tb_equipment (id),
    CONSTRAINT fk_solicitation_project FOREIGN KEY (project_id) REFERENCES public.tb_project (id),
    CONSTRAINT fk_solicitation_analysis FOREIGN KEY (analysis_id) REFERENCES public.tb_analysis (id)
);

-- public.tb_student_solicitation definition
-- Drop table
-- DROP TABLE public.tb_student_solicitation;
CREATE TABLE public.tb_student_solicitation
(
    id            int8      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    creation_date timestamp NULL,
    finish_date   timestamp NULL,
    status        int4      NULL,
    finished_by   int8      NULL,
    solicited_by  int8      NULL,
    solicited_to  int8      NULL,
    CONSTRAINT tb_student_solicitation_pkey PRIMARY KEY (id),
    CONSTRAINT fk_student_solicitation_user_to FOREIGN KEY (solicited_to) REFERENCES public.tb_user (id),
    CONSTRAINT fk_student_solicitation_user_finished FOREIGN KEY (finished_by) REFERENCES public.tb_user (id),
    CONSTRAINT fk_student_solicitation_user_by FOREIGN KEY (solicited_by) REFERENCES public.tb_user (id)
);

-- public.tb_student_professor definition
-- Drop table
-- DROP TABLE public.tb_student_professor;
CREATE TABLE public.tb_student_professor
(
    id         int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    approved   bool NULL,
    created_at date NULL,
    student    int8 NULL,
    professor  int8 NULL,
    CONSTRAINT tb_student_teacher_pkey PRIMARY KEY (id),
    CONSTRAINT fk_student_teacher_student FOREIGN KEY (student) REFERENCES public.tb_user (id),
    CONSTRAINT fk_student_teacher_professor FOREIGN KEY (professor) REFERENCES public.tb_user (id)
);

-- public.tb_transaction definition
-- Drop table
-- DROP TABLE public.tb_transaction;
CREATE TABLE public.tb_transaction
(
    id              int8           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp      NULL,
    description     varchar(255)   NULL,
    total_value     numeric(19, 2) NULL,
    created_by      int8           NULL,
    updated_by      int8           NULL,
    solicitation_id int8           NULL,
    user_id         int8           NULL,
    CONSTRAINT tb_transaction_pkey PRIMARY KEY (id),
    CONSTRAINT fk_transaction_created FOREIGN KEY (created_by) REFERENCES public.tb_user (id),
    CONSTRAINT fk_transaction_updated FOREIGN KEY (updated_by) REFERENCES public.tb_user (id),
    CONSTRAINT fk_transaction_solicitation FOREIGN KEY (solicitation_id) REFERENCES public.tb_solicitation (id),
    CONSTRAINT fk_transaction_user FOREIGN KEY (user_id) REFERENCES public.tb_user (id)
);


-- public.tb_solicitationHistoric definition
-- Drop table
-- DROP TABLE public.tb_solicitationHistoric;
CREATE TABLE public.tb_solicitation_historic
(
    id              int8          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp     NULL,
    status          int4          NULL,
    observation     varchar(2048) NULL,
    solicitation_id int8          NULL,
    created_by      int8          NULL,
    CONSTRAINT audit_pkey PRIMARY KEY (id),
    CONSTRAINT fk_solicitation_historic_solicitation FOREIGN KEY (solicitation_id) REFERENCES public.tb_solicitation (id),
    CONSTRAINT fk_solicitation_historic_created_by FOREIGN KEY (created_by) REFERENCES public.tb_user (id)
);


-- public.tb_solicitation_attachments definition
-- Drop table
-- DROP TABLE public.tb_solicitation_attachments;
CREATE TABLE public.tb_solicitation_attachments
(
    id              int8          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content_type    varchar(255)  NULL,
    file_name       varchar(255)  NULL,
    url             varchar(2048) NULL,
    solicitation_id int8          NULL,
    CONSTRAINT tb_solicitation_attachments_pkey PRIMARY KEY (id),
    CONSTRAINT fk_solicitation_attachments_solicitation FOREIGN KEY (solicitation_id) REFERENCES public.tb_solicitation (id)
);

-- public.tb_domain_role definition
-- Drop table
-- DROP TABLE public.tb_domain_role;
CREATE TABLE public.tb_domain_role
(
    id     int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    domain varchar(255) NULL,
    role   int4         NULL,
    CONSTRAINT tb_domain_role_pkey PRIMARY KEY (id),
    CONSTRAINT unique_domain_role UNIQUE (domain)
);