-- Cria as tabelas
-- public.tb_email_config definition
-- Drop table
-- DROP TABLE public.tb_email_config;
CREATE TABLE public.tb_email_config (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NULL,
    password varchar(255) NULL,
    host varchar(255) NULL,
    port int4 NULL,
    CONSTRAINT tb_email_config_pkey PRIMARY KEY (id)
);


-- public.equipment definition
-- Drop table
-- DROP TABLE public.equipment;
CREATE TABLE public.tb_equipment (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(512) NULL,
    short_name varchar(255) NULL,
    model varchar(255) NULL,
    status int4 NULL,
    value_hour_partner numeric(19, 2) NULL,
    value_hour_external numeric(19, 2) NULL,
    value_hour_utfpr numeric(19, 2) NULL,
    value_sample_partner numeric(19, 2) NULL,
    value_sample_external numeric(19, 2) NULL,
    value_sample_utfpr numeric(19, 2) NULL,
    CONSTRAINT tb_equipment_pkey PRIMARY KEY (id)
);

-- public.partner definition
-- Drop table
-- DROP TABLE public.partner;
CREATE TABLE public.tb_partner (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NULL,
    cnpj varchar(18) NULL,
    status varchar(255) NULL,
    CONSTRAINT tb_partner_pkey PRIMARY KEY (id)
);


-- public.tb_email definition
-- Drop table
-- DROP TABLE public.tb_email;
CREATE TABLE public.tb_email_log (
    id int8 NOT NULL,
    email_from varchar(255) NULL,
    email_to varchar(255) NULL,
    owner_ref varchar(255) NULL,
    send_date_email timestamp NULL,
    status_email int4 NULL,
    subject varchar(255) NULL,
    "text" text NULL,
    CONSTRAINT tb_email_log_pkey PRIMARY KEY (id)
);

-- public.users definition
-- Drop table
-- DROP TABLE public.users;
CREATE TABLE public.users (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    balance numeric(19, 2) NULL,
    cpf_cnpj varchar(25) NULL,
    created_at timestamp NULL,
    email varchar(255) NULL,
    email_verified bool NULL,
    "name" varchar(255) NULL,
    "password" varchar(255) NULL,
    raSiape varchar(25) NULL,
    "role" int4 NULL,
    status int4 NULL,
    updated_at timestamp NULL,
    partner_id int8 NULL,
    CONSTRAINT set_unique_email UNIQUE (email),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user_partner FOREIGN KEY (partner_id) REFERENCES public.tb_partner(id)
);

-- public.email_code definition
-- Drop table
-- DROP TABLE public.email_code;
CREATE TABLE public.email_code (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code varchar(255) NULL,
    created_at timestamp NULL,
    validate_at timestamp NULL,
    user_id int8 NULL,
    CONSTRAINT email_code_pkey PRIMARY KEY (id),
    CONSTRAINT fkp50i69palc7sgmpjtxr0ruky1 FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- public."permission" definition
-- Drop table
-- DROP TABLE public."permission";
CREATE TABLE public."permission" (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "action" int4 NULL,
    description varchar(50) NOT NULL,
    user_id int8 NULL,
    CONSTRAINT permission_pkey PRIMARY KEY (id),
    CONSTRAINT fktpvwdvckg86mpuk9o2j1h6t15 FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- public.project definition
-- Drop table
-- DROP TABLE public.project;
CREATE TABLE public.project (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description varchar(255) NULL,
    subject varchar(255) NULL,
    user_id int8 NULL,
    CONSTRAINT project_pkey PRIMARY KEY (id),
    CONSTRAINT fk_project_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.project_student definition
-- Drop table
-- DROP TABLE public.project_student;
CREATE TABLE public.project_student (
    project_id int8 NOT NULL,
    user_id int8 NOT NULL,
    CONSTRAINT fkrwrqi8lnwc20jdsl0di7595dt FOREIGN KEY (project_id) REFERENCES public.project(id),
    CONSTRAINT fksfigybcnck4hluwvcmwhncaji FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- public.solicitation definition
-- Drop table
-- DROP TABLE public.solicitation;
CREATE TABLE public.solicitation (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description varchar(255) NULL,
    form jsonb,
    project_nature varchar(255) NULL,
    other_project_nature varchar(255) NULL,
    status int4 NULL,
    amount_hours float4 NULL,
    amount_samples int4 NULL,
    price numeric(19, 2) NULL,
    total_price numeric(19, 2) NULL,
    user_id int8 NULL,
    professor_id int8 NULL,
    user_updated_id int8 NULL,
    equipment_id int8 NULL,
    project_id int8 NULL,
    CONSTRAINT solicitation_pkey PRIMARY KEY (id),
    CONSTRAINT fk_solicitation_user FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fk_solicitation_professor FOREIGN KEY (professor_id) REFERENCES public.users(id),
    CONSTRAINT fk_solicitation_user_update FOREIGN KEY (user_updated_id) REFERENCES public.users(id),
    CONSTRAINT fk_solicitation_equipment FOREIGN KEY (equipment_id) REFERENCES public.tb_equipment(id),
    CONSTRAINT fk_solicitation_project FOREIGN KEY (project_id) REFERENCES public.project(id)
);

-- public.student_solicitation definition
-- Drop table
-- DROP TABLE public.student_solicitation;
CREATE TABLE public.student_solicitation (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    creation_date timestamp NULL,
    finish_date timestamp NULL,
    status int4 NULL,
    finished_by int8 NULL,
    solicitated_by int8 NULL,
    solicitated_to int8 NULL,
    CONSTRAINT student_solicitation_pkey PRIMARY KEY (id),
    CONSTRAINT fkcr5ggvawb7p0nb6lp174eh93q FOREIGN KEY (solicitated_to) REFERENCES public.users(id),
    CONSTRAINT fkcsa8jdevheox1spo9l7ik97jj FOREIGN KEY (finished_by) REFERENCES public.users(id),
    CONSTRAINT fkmifnpcha0rdj2xk1a86dvhkqv FOREIGN KEY (solicitated_by) REFERENCES public.users(id)
);

-- public.student_teacher definition
-- Drop table
-- DROP TABLE public.student_teacher;
CREATE TABLE public.student_teacher (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    aproved bool NULL,
    created_at date NULL,
    student int8 NULL,
    teacher int8 NULL,
    CONSTRAINT student_teacher_pkey PRIMARY KEY (id),
    CONSTRAINT fkec7eqsd3889dvckiddeud9q5o FOREIGN KEY (student) REFERENCES public.users(id),
    CONSTRAINT fklrr40d5nsa0esws0r4an2vw5q FOREIGN KEY (teacher) REFERENCES public.users(id)
);

-- public."transaction" definition
-- Drop table
-- DROP TABLE public."transaction";
CREATE TABLE public."tb_transaction" (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp NULL,
    description varchar(255) NULL,
    total_value numeric(19, 2) NULL,
    created_by int8 NULL,
    updated_by int8 NULL,
    solicitation_id int8 NULL,
    user_id int8 NULL,
    CONSTRAINT transaction_pkey PRIMARY KEY (id),
    CONSTRAINT fk_transaction_created FOREIGN KEY (created_by) REFERENCES public.users(id),
    CONSTRAINT fk_transaction_updated FOREIGN KEY (updated_by) REFERENCES public.users(id),
    CONSTRAINT fk_transaction_solicitation FOREIGN KEY (solicitation_id) REFERENCES public.solicitation(id),
    CONSTRAINT fk_transaction_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.solicitationHistoric definition
-- Drop table
-- DROP TABLE public.solicitationHistoric;
CREATE TABLE public.tb_solicitation_historic (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp NULL,
    status int4 NULL,
    solicitation_id int8 NULL,
    created_by int8 NULL,
    CONSTRAINT audit_pkey PRIMARY KEY (id),
    CONSTRAINT fk_solicitation_historic_solicitation FOREIGN KEY (solicitation_id) REFERENCES public.solicitation(id),
    CONSTRAINT fk_solicitation_historic_created_by FOREIGN KEY (created_by) REFERENCES public.users(id)
);


-- public.tb_solicitation_attachments definition
-- Drop table
-- DROP TABLE public.tb_solicitation_attachments;
CREATE TABLE public.tb_solicitation_attachments (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content_type varchar(255) NULL,
    file_name varchar(255) NULL,
    url varchar(2048) NULL,
    solicitation_id int8 NULL,
    CONSTRAINT tb_solicitation_attachments_pkey PRIMARY KEY (id),
    CONSTRAINT fk_solicitation_attachments_solicitation FOREIGN KEY (solicitation_id) REFERENCES public.solicitation(id)
);

-- public.domain_role definition
-- Drop table
-- DROP TABLE public.domain_role;
CREATE TABLE public.domain_role (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "domain" varchar(255) NULL,
    "role" int4 NULL,
    CONSTRAINT domain_role_pkey PRIMARY KEY (id),
    CONSTRAINT unique_domain_role UNIQUE (domain)
);